### ISSUE TITLE
An alternative minimal approach

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [hurufu/prolog-all#1]
This is not to lower your efforts, which are deeply appreciated.
Just for the record in case somebody is interested in the future.

An alternative minimal approach, which already
works on many Prolog systems is to only require:
```
<prolog system> <prolog script>
```
And inside the Prolog text <prolog script>:
```
:- initialization(my_main)
```
The initialization/1 directive is from the
ISO core standard. You find some words

about it here:

> **:- initialization(:Goal)**
https://www.swi-prolog.org/pldoc/man?predicate=initialization/1

**Comment by Jean-Luc-Picard-2021** [comment]
P.S.: Next level is option processing, the minimal being:
```
<prolog system> <prolog script> <option 1> ... <option n>
```
But things get very hairy here, for example
SWI-Prolog allows multiple prolog scripts depending
whether it sees an extension `.pl` on the command line.

And inside the Prolog text you can access the options via:
```
my_main :-
   current_prolog_flag(argv, L),
   /* your option logic */
```
Its not in the ISO core standard but also quite common:

> **argv(list, changeable)**
>    List is a list of atoms representing the
>    application command line arguments.
> https://www.swi-prolog.org/pldoc/doc_for?object=current_prolog_flag/2

You can then define options that control your Prolog
program semantically without exposing Prolog code.
The command line DSL of your Prolog program can

be anything need not be Prolog goals. This gives
a more flexible command line interface, since you
can more easily change the implementation,

than when you expose Prolog goals. The command
line DSL can also solve escaping problems different
than the way they can happen with supplying Prolog goals.

**Comment by hurufu** [comment]
First of all thank you for visiting this repo.

Trick using `:- initialization(goal)` is indeed very minimal and works well for some Prologs, but sadly not for all of them. One of my motivations is also a wish to "resurrect" cool historical Prologs (like Gödel or KL1) basically everything that has compatible syntax and test them too. Why not‽

Regarding option processing, I agree it is a mess in Prolog, I don't think I will want to even try unifying it.

At this moment even consulting more than one file doesn't work for some Prologs.

**Comment by Jean-Luc-Picard-2021** [comment]
In some Prolog systems, you can bootstrap `initialization/1` as follows,
just create a kind of "compatibility" file, Logtalk would call it an adapter,
but I don't want to go as far as creating a Logtalk, with this definition:
```
/* ISO core standard initialization/1 cludge */
initialization(X) :- X.
```
But I recently noticed that despite not all Prolog systems allow to
define so easily a custom initialization/1 directive, they refuse
to accept arbitrary goals as directive, I had also some

locking problem in formerly Jekejeke Prolog. So I am now following
the approach that initialization/1 does push the given goal
on a list, and executes all pushed goals when it has completing

consulting all files. SWI-Prolog has even finer control over 
the "when" the goal gets executed via its initialization/2 variant,
where there is a 2nd when parameter:

> **initialization(:Goal, +When)**
https://www.swi-prolog.org/pldoc/man?predicate=initialization/2

**Comment by Jean-Luc-Picard-2021** [comment]
How to obtain Prolog systems from the past, such as "Gödel". I 
have no clue, in the past you had this mysterious system administrators 
that loaded your pizza box (SUN microsystems station)

with a bouquet of Prolog systems (in minimum C-Prolog and SICStus), 
mainly by mounting some network drive, which had all the executables 
imaginable from people far and near visiting the university. But I 

wouldn't shy away from writing emails to people that are still alive, like:

> **John W. Lloyd**
https://users.cecs.anu.edu.au/~jwl/
Who else?

The software preservation group does such things full time?

> **Prolog and Logic Programming Historical Sources Archive**
https://www.softwarepreservation.org/projects/prolog

But the "Gödel" project from Hill and Lloyd is indeed not listed.
Maybe I didn't look at the right place?

**Comment by hurufu** [comment]
I have found this gem: https://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/lang/prolog/impl/other/goedel/v1_4/ It even contains sources, I didn't try to compile them yet, but I have started with KL1 from the 5th Gen Computer Systems. It compiles, but I didn't manage to run it yet, because some emulation software is needed that will emulate those parallel Prolog machines.

**Comment by hurufu** [comment]
I have found this gem: https://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/lang/prolog/impl/other/goedel/v1_4/ It even contains sources, but I didn't try to compile them, but I have started with KL1 from the 5th Gen Computer Systems. It compiles, but I didn't manage to run it yet, because some emulation software is needed that will emulate those parallel Prolog machines.

**Comment by Jean-Luc-Picard-2021** [comment]
Thats probably from the CMU Artificial Intelligence Repository,
made by Mark Kantrowitz in the 90's. Yeah thats an execellent source. 

https://www.cs.cmu.edu/Groups/AI/0.html

You also find an early λ-Prolog there, `lp2.7`.
